<a href="https://colab.research.google.com/github/m4hdiattar/ARTE/blob/master/NAND_hopfield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files.upload()

Saving HopfieldNetwork.py to HopfieldNetwork.py


{'HopfieldNetwork.py': b'# -*- coding: utf-8 -*-\n"""HopfieldNetwork\n\nAutomatically generated by Colaboratory.\n\nOriginal file is located at\n    https://colab.research.google.com/drive/1ADKD7igOfJYJq1EBZdA0cWGEbJLw16fX\n"""\n\n# This file implements the generic methods related to a binary Hopfield network.\n# I wanted to mantain (more or less) the same structure as the Mathematica\n# files.\n\n# I import the numpy library, which allows\n# to perform numerical operations quickly\nimport numpy as np\n\n# I import the random module\nimport random\n\n# I import the itertools module\nimport itertools\n\n# I import the copy module\nimport copy\n\n# Hopfield class\nclass HopfieldNetwork:\n\n    # Constructor method\n    def __init__(self, n, weight, b):\n\n        # I store the dimension\n        self.n = n  \n        # I store the b vector, which affects\n        # the activate function, generalizing it\n        self.b = b\n        # I create an empty list to store the states\n        # 

In [3]:
import numpy as np

import HopfieldNetwork

n = 8

weight_value =  0
b = [0.]*n
strictly = 0
patt = [[1,1,0,0,0,0,1,1],[1,1,0,0,1,1,0,0]]
Init = [[1,0,0,1,0,1,1,0], [1,0,0,1,1,0,0,1], [0,1,1,0,0,1,1,0], [0,1,1,0,1,0,0,1], [0,0,1,1,0,1,1,0], [0,0,1,1,1,0,0,1], [1,1,0,0,0,1,1,0], [1,1,0,0,0,1,0,1],[1,0,0,1,0,0,0,0],[1,0,0,1,1,1,1,1],[0,1,1,0,0,0,0,0],[0,1,1,0,1,1,1,1],[1,1,0,0,0,0,1,1],[1,1,0,0,1,1,0,0], [0,0,1,1,0,0,1,1], [0,0,1,1,1,1,0,0]]

out = list(range(2))
Out = list(range(2))
evolutions = list(range(len(Init)))
Pattern = list(range(5))
KK = list(range(30))
LL = list(range(30))
II = list(range(30))
JJ = list(range(30))
KKK = list(range(30))
NAND = 0

import itertools
pattern = list(range(256))
from itertools import product
pattern = [list(i) for i in itertools.product([0, 1], repeat=8)]

pattern.remove(patt[0])
pattern.remove(patt[1])

Pattern[0] = patt[0]
Pattern[1] = patt[1]
m = 0
with open('outpout_data.txt', 'w') as out_file:
  for I in range(len(pattern)-2):
    if m == len(Init):
      break
    else:
      m = 0
      for J in range(I+1,len(pattern)-1):
        if m == len(Init):
          break
        else:
          m = 0
          for K in range(J+1, len(pattern)):
            if m == len(Init):
              break
            else:
              m = 0
              Pattern[2] = pattern[I]
              Pattern[3] = pattern[J]
              Pattern[4] = pattern[K]
            
              weight = -weight_value * np.ones([n,n])
              for p in range(5):
                  for i in range(n):
                      for j in range(n):
                          # Different cases in which I have to modify the matrix element
                          if i == j: weight[i,j] = 0
                          else: weight[i,j] = weight[i,j]+(2 * Pattern[p][i] - 1) * (2 * Pattern[p][j] - 1)

              # print('weight = ', weight)
              hop = HopfieldNetwork.HopfieldNetwork(n, weight, b)
              z = 0
              for state in Init:
                  evolution_states_scan = hop.hopfield('scan', weight, state, 5)
                  evolutions[z] = evolution_states_scan[-1]
                  z += 1
              
              for k in range(n-1): 
                if m == len(Init):
                  break
                else:
                  m == 0
                  for l in range(k + 1,n):
                      if m == len(Init):
                        break
                      else:
                        m = 0
                      print(weight)
                      print('                      ')
                      print('                      ')
                      print('Pattern', Pattern)
                      print('                      ')
                      print('                      ')
                      print('out-1 =>>', k + 1 , '  ', 'out-2 =>>', l + 1 )

                      out_string1 = 'Patterns:' + str(Pattern) + '\n'
                      out_file.write(out_string1)  
                      out_string2 = '              ' + 'out-1:' + str(Out[0]) + '   &   ' + 'out-2:' + str(Out[1]) + '\n'
                      out_file.write(out_string2)

                      for s in range(len(Init)):
                          state = Init[s]
                          Out[0] = evolutions[s][k]
                          Out[1] = evolutions[s][l]
                          print('                           ')
                          print('                           ')
                          print('=>>>>> state  ', state)
                          print('=>>>>> output ', evolutions[s])

                          # out_file.write('\n')
                          out_string3 = 'state: ' + str(state) + '\n' + 'output: ' + str(evolutions[s]) + '\n' 
                          out_file.write(out_string3) 

                          if state == [1, 1, 0, 0, 0, 0, 1, 1] or state == [1, 1, 0, 0, 1, 1, 0, 0] or state == [0, 0, 1, 1, 0, 0, 1, 1] or state == [0, 0, 1, 1, 1, 1, 0, 0] :
                              out[0] = [1.0, 0.0]
                              out[1] = [0.0, 1.0]
                          else:
                              out[0] = [1.0, 1.0]
                              out[1] = [0.0, 0.0]
                              
                          if Out == out[0] or Out == out[1]:
                              m += 1
                              print(Out, '==', out)
                              out_string4 = str(Out) + ' == ' + str(out) + '\n'
                              out_file.write(out_string4)
                              # print('m=', m)
                          else:
                              # print('m = ', m)
                              print(Out, '=!', out)
                              out_string4 = str(Out) + ' =! ' + str(out) + '\n'
                              out_file.write(out_string4)
                                                        
                  
                      print('NO. of correct Association = ', m)
                      # out_file.write('\n')
                      out_string5 = 'NO. of correct Association = ' + str(m) + '\n'
                      out_file.write(out_string5)
                      print('                               ' )

                      if m == len(Init):
                        NAND += 1
                        KK[NAND] = k
                        LL[NAND] = l
                        II[NAND] = I
                        JJ[NAND] = J
                        KKK[NAND] = K
                        
                        break
                              
  print(k, l, I, J, K)                          

Streaming output truncated to the last 5000 lines.
                           
=>>>>> state   [0, 0, 1, 1, 1, 1, 0, 0]
=>>>>> output  [0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
[0.0, 0.0] =! [[1.0, 0.0], [0.0, 1.0]]
NO. of correct Association =  12
                               
[[ 0.  3.  1. -1.  1. -1.  1. -1.]
 [ 3.  0. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  0.  3.  1. -1.  1. -1.]
 [-1.  1.  3.  0. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  0.  3.  1. -1.]
 [-1.  1. -1.  1.  3.  0. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.  0.  3.]
 [-1.  1. -1.  1. -1.  1.  3.  0.]]
                      
                      
Pattern [[1, 1, 0, 0, 0, 0, 1, 1], [1, 1, 0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 1, 1], [0, 1, 0, 1, 0, 1, 0, 1]]
                      
                      
out-1 =>> 1    out-2 =>> 3
                           
                           
=>>>>> state   [1, 0, 0, 1, 0, 1, 1, 0]
=>>>>> output  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0] == [[1.0, 1.0], [0.

In [40]:
len(Init)
print(Init)

[[1, 0, 0, 1, 0, 1, 1, 0], [1, 0, 0, 1, 1, 0, 0, 1], [0, 1, 1, 0, 0, 1, 1, 0], [0, 1, 1, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 1, 1, 0], [0, 0, 1, 1, 1, 0, 0, 1], [1, 1, 0, 0, 0, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1], [1, 0, 0, 1, 0, 0, 0, 0], [1, 0, 0, 1, 1, 1, 1, 1], [0, 1, 1, 0, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 1, 1], [1, 1, 0, 0, 0, 0, 1, 1], [1, 1, 0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0, 1, 1], [0, 0, 1, 1, 1, 1, 0, 0]]
